### ISSUE TITLE
"loop-file=inf" causes infinite encode

### ISSUE THREAD

**Issue by dmerge** [ElegantMonkey/mpv-webm#11]
`loop-file=inf` set causes an infinite concatenated encode. Terminating the process or CTRL+C in terminal outputs "Encode failed! Check the logs for details", but no sign of any log or logs (checked home directory, working directory, and mpv config directory, and also grepped recursively for filename). Haven't looked at the source, but the lua script doesn't appear to save a log?
Using webm.lua from git, mpv git.

**Comment by ElegantMonkey** [comment]
>but the lua script doesn't appear to save a log

It doesn't (by itself), it outputs to the mpv log. Use the `--log-file` flag.

As for the loop-file flag, I'm not sure how to fix this. I could override it with `loop-file=no`, but maybe there are cases where looping inside the encode is desirable?

**Comment by dmerge** [comment]
> It doesn't (by itself), it outputs to the mpv log.

Oh - that should have been obvious. But of course there's nothing there as no encoding error.

I don't see how inheriting this option if present is desirable given that it doesn't honour the target filesize set in the script, and it never finishes encoding, just grows the output file indefinitely while encoding the same data over and over.
