### ISSUE TITLE
Output as same filetype as input?

### ISSUE THREAD

**Issue by frozenpandaman** [ElegantMonkey/mpv-webm#22]
Hi,

Would it be possible to add an option to output to the same format as the input file, e.g. if playing an mp4, the crop, timestamp, and selected mute/subtitle/etc. filters would still be applied, but the video wouldn't be changed into a webm or avi? This would be super helpful (and possibly easy to do – similar to the webm option just without the passing the `-c:v` filter?) Thanks!

**Comment by ElegantMonkey** [comment]
Possibly a duplicate of #8. Unfournately, mpv doesn't support copying codecs (and even if it did, it doesn't always give the desired effect).

Unless you mean mirroring the input's audio and video codec, which should be doable...

**Comment by frozenpandaman** [comment]
I see. That'd be similar, though I think would snap to keyframes, so the output clip wouldn't get cut at the exact times, right?

How about an option to convert to mp4, then?

**Comment by ElegantMonkey** [comment]
I'll probably do it when I get a bit of free time, shouldn't be too hard.

**Comment by frozenpandaman** [comment]
Sounds great, thank you! I'll look forward to it. I tried fooling with myself it but I'm super familiar with Lua, otherwise I'd make a PR.

**Comment by ElegantMonkey** [comment]
I've added it, however, on the mpv build I use, the embedded libx264 has no 10-bit support, so I couldn't test it.

**Comment by frozenpandaman** [comment]
@ElegantMonkey Seems to work for me! Thank you so much! Super appreciated.
