### ISSUE TITLE
[Request]Possibility to add "leave as/use current format" ?

### ISSUE THREAD

**Issue by Broky** [ElegantMonkey/mpv-webm#26]
Hey man,

just a quick question if there's the possibility to add an encoding option to just use the current format?

I.e. I'm mainly converting from .ts files, so for files that just need to be cut and not converted, i could 'abuse' mpv-webm as cutter without switching to another tool.

Greetings broky

**Comment by ElegantMonkey** [comment]
Possibly duplicate of #8.

mpv doesn't support "copy" codecs, therefore "cutting" without reencoding can't be done.

**Comment by Broky** [comment]
Yeah, looks like i missed that, sorry.

Anyway thanks for your time and immediate reply, admittedly i too thought you'd use ffmpeg.
But i guess it was worth a try.

Godspeed
